# Website settings
url: "http://www.bryancovell.com"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "https://www.flickr.com/photos/brikis98/albums/"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Bryan Covell" # home button, copyright, etc gets this text
description: "The Website of Bryan Covell. Forked from Yevgeniy Brikman."
thumbnail_path: "profile-photos/bryan-professional-square.jpg"
website_repo_url: "https://github.com/bpc6/bpc6.github.io"
# terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/bryancovell/"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/bryan.covell.79"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/bpc6"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:bpcovell@gmail.com"
    label: "Email"
    value: "bpcovell@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/New_York'
repository: bpc6/bpc6.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
